version: 2

python:
  version: 3.7
  install:
    - requirements: docs/docs-requirements.txt
    - requirements: requirements.txt
    - method: pip
    - path: .

sphinx:
  configuration: docs/conf.py
